In [9]:
import numpy as np

In [10]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[2,1,1],[2,2,2]])



In [11]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
B

array([[2, 1, 1],
       [2, 2, 2]])

In [13]:
A-B

array([[-1,  1,  2],
       [ 2,  3,  4]])

# multiplication

In [16]:
X = np.random.randn(50000, 4)

W = np.random.randn(4,1)

Z = np.dot(X, W)
print(Z.shape)

(50000, 1)


# with Bias

In [2]:
import numpy as np


X = np.array([[22,7],
              [35,50],
              [18,12]]) # (3*2)

Y = np.array([[1],
              [3],
              ]) #(2*1)

b = -1.2



z = X @ Y + b

print(z)

[[ 41.8]
 [183.8]
 [ 52.8]]


In [9]:
X_original = np.array([[22, 7],
                       [35, 50],
                       [18, 12]])

X_with_bias = np.hstack([np.ones((X_original.shape[0], 1)), X_original])

print(X_with_bias)

W_combined = np.array([[-1.2], 
                       [ 0.1],  
                       [ 0.5]]) 




z = X_with_bias @ W_combined
print(z)

[[ 1. 22.  7.]
 [ 1. 35. 50.]
 [ 1. 18. 12.]]
[[ 4.5]
 [27.3]
 [ 6.6]]
