In [9]:
import numpy as np

In [10]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[2,1,1],[2,2,2]])



In [11]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
B

array([[2, 1, 1],
       [2, 2, 2]])

In [13]:
A-B

array([[-1,  1,  2],
       [ 2,  3,  4]])

# multiplication

In [16]:
X = np.random.randn(50000, 4)

W = np.random.randn(4,1)

Z = np.dot(X, W)
print(Z.shape)

(50000, 1)
